# @package _global_

defaults:
  
  - data: sepsis #options: sepsis, bpic, emergency
  - model: tf_decoder #options: cvae, tf_decoder
  - test_cfg: beam #options: original, beam
  - logger: null
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default
  - _self_

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ???